### ISSUE TITLE
thread 'main' panicked at 'missing mempool tx feeinfo

### ISSUE THREAD

**Issue by Kexkey** [Blockstream/esplora#74] opened 2019-04-18 16:08 UTC
Hi,

Our esplora instance crashed yesterday.  Logs from `electrs-bitcoin.log`:

```
...
thread 'main' panicked at 'missing mempool tx feeinfo 8a1136da677c5a550f435de401cbda0f7df1783e19d6c81bd6b3ac38e5add286', src/libcore/option.rs:1008:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2019-04-17T02:28:58.056+00:00 - TRACE - stop accepting new RPCs
2019-04-17T02:28:58.057+00:00 - TRACE - closing 0 RPC connections
2019-04-17T02:28:58.057+00:00 - TRACE - waiting for 0 RPC handling threads
2019-04-17T02:28:58.057+00:00 - TRACE - RPC connections are closed
2019-04-17T02:28:58.057+00:00 - TRACE - RPC server is stopped
2019-04-17T02:28:58.058+00:00 - TRACE - Notifier::notify; id=0x7ff4680410b0
2019-04-17T02:28:58.058+00:00 - TRACE - submit to existing worker; idx=2; state=worker::State { lifecycle: Sleeping, is_pushed: true }
2019-04-17T02:28:58.058+00:00 - TRACE -     -> wakeup; idx=2
2019-04-17T02:28:58.058+00:00 - TRACE - found work while draining; signal_work
2019-04-17T02:28:58.058+00:00 - TRACE - signal_work -- wakeup; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE - Task::run; state=Running
2019-04-17T02:28:58.058+00:00 - DEBUG - signal received, starting graceful shutdown
2019-04-17T02:28:58.058+00:00 - TRACE -     -> wakeup; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE - Worker::sleep; worker=WorkerId(3)
2019-04-17T02:28:58.058+00:00 - TRACE -   sleeping -- push to stack; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE -     -> starting to sleep; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE - deregistering handle with poller
2019-04-17T02:28:58.058+00:00 - DEBUG - dropping I/O source: 0
2019-04-17T02:28:58.058+00:00 - TRACE -     -> task complete
2019-04-17T02:28:58.058+00:00 - TRACE - task complete; state=pool::State { lifecycle: ShutdownNow, num_futures: 0 }
2019-04-17T02:28:58.058+00:00 - TRACE -   -> shutting down workers
2019-04-17T02:28:58.058+00:00 - TRACE -     -> wakeup; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE - shutting down thread; idx=2
2019-04-17T02:28:58.058+00:00 - TRACE -     -> wakeup; idx=1
2019-04-17T02:28:58.058+00:00 - TRACE - shutting down thread; idx=3
2019-04-17T02:28:58.058+00:00 - TRACE - shutting down thread; idx=1
2019-04-17T02:28:58.058+00:00 - TRACE -     -> wakeup; idx=0
2019-04-17T02:28:58.058+00:00 - TRACE - shutting down thread; idx=0
2019-04-17T02:28:58.059+00:00 - TRACE - event Readable Token(4194303)
2019-04-17T02:28:58.059+00:00 - DEBUG - loop process - 1 events, 0.000s
2019-04-17T02:28:58.059+00:00 - DEBUG - shutting background reactor on idle
2019-04-17T02:28:58.059+00:00 - DEBUG - background reactor has shutdown
...
```

I have a sub-question: After the restart (at 02:29), it re-downloaded the 571968 block headers and the pre-caching process took about 3 hours and a half.  Esplora came back fully working at 06:00.  Is it normal to redownload all the headers?  Also, if I disable the pre-caching, what is the impact on usability?

Thanks!

**Comment by shesek** [comment] 2019-04-18 23:17
Thanks for the report, I'll look into this.

> Is it normal to redownload all the headers? 

It is the currently expected behavior, but not the optimal one. All of the information is also available on the local rocksdb database and could be loaded from there instead of fetching it from bitcoind, which is of course preferable. I created #76 to keep track of that.

> Also, if I disable the pre-caching, what is the impact on usability?

The pre-cache calculates aggregated stats and the UTXO set for popular addresses ([the ones in this list](https://github.com/Blockstream/electrs/blob/new-index/contrib/popular-scripts.txt)). If you don't pre-cache, this means that the first user to request a popular address would experience some delay while the server is crunching the numbers. The results will get cached though, such that the server will only have to process the delta of new transactions the next time a user requests that address.

The pre-cache also does delta updates, so it shouldn't really take long after the first time you do it. I'm quite surprised it took over 3 hours. How long was the server running for before this restart?

**Comment by shesek** [comment] 2019-04-18 23:24
Can you check if there's an earlier warning in the logs with the message "lookup txouts failed"? It could be somewhere in the 30-40 minutes before the crash.

**Comment by Kexkey** [comment] 2019-04-23 14:29
Hi shesek!  So I looked in the logs and saw the crash happened several times since I opened the issue.  You are right, I can see the lookup txouts failed warning about 3-4 minutes before the crash.  The txid is not the same as the crash, though.

```
...
2019-04-19T16:05:01.926+00:00 - WARN - reconnecting to bitcoind: disconnected from daemon while receiving
2019-04-19T16:05:19.061+00:00 - WARN - lookup txouts failed: missing outpoint OutPoint { txid: be3cf05e41fefbcab7790b4c2cf2d4232442c6b850a500517cb2a6a814fa593d, vout: 0 }
2019-04-19T16:05:24.257+00:00 - DEBUG - downloading new block headers (572336 already indexed) from 00000000000000000029273f2b925a3a160fef51fb931a5b540c5f011beb652f
...
2019-04-19T16:08:09.562+00:00 - DEBUG - writing 0 rows to RocksDB { path: "/data/electrs_bitcoin_db/mainnet/mainnet/newindex/history" }, flush=Enable
thread 'main' panicked at 'missing mempool tx feeinfo 5af4da6af8a78d20660caa1ffbedfb442b1bae03bced26ba1640c2ec73b2f81a', src/libcore/option.rs:1008:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2019-04-19T16:08:10.804+00:00 - TRACE - stop accepting new RPCs
...
```

**Comment by shesek** [comment] 2019-04-23 14:39
The root cause is still not entirely clear to me, but 48ec50666405709fa286bf6a0859653920105f65 should prevent the daemon from crashing when that happens.

How large is your bitcoind mempool configured to be (`maxmempool`)?

**Comment by Kexkey** [comment] 2019-04-23 14:57
I didn't change the `maxmempool` setting and I don't see it set in esplora's bitcoin.conf file (`/data/.bitcoin.conf` in the container), so I guess it's the default value of 300.

**Comment by shesek** [comment] 2019-04-26 01:22
The ` reconnecting to bitcoind: disconnected from daemon while receiving` message is interesting and possibly related, are you seeing more of these? Any other relevant log message showing up before this?

**Comment by shesek** [comment] 2019-06-22 02:29
@Kexkey #76 was implemented, it should no longer re-download all the headers on startup.

I'm closing this issue for now, please report back if you're running into this again.

**Closed by shesek** 2019-06-22 02:29 UTC
Labels: bug
