### ISSUE TITLE
Questions - Confirmation Count, Request Throttling

### ISSUE THREAD

**Issue by mcDingleHead** [Blockstream/esplora#126] opened 2019-07-28 22:18 UTC
I've been using your public API successfully for a while now. A couple of questions:

(1) When viewing a transaction result, which field contains the number of confirmations that have taken place? Right now, as an estimate, I'm subtracting the block_time from the current time, converting to minutes, and dividing by 10 -- my thought being that each confirmation takes around 10 mins. But is there a better way? I see that the transaction's block number is available, but without knowing the current block, there's no way to deduce the number of confirmations.

(2) A lot of the public Bitcoin explorer APIs that I use have limits on how many queries per second can be executed (e.g. no more than fifteen queries per minute). What are the limits for the API located at https://blockstream.info/api/... ? I want to code my app not to exceed the desired limits.

thanks,

mcDingleHead

**Comment by mcDingleHead** [comment] 2019-08-14 04:43
Hey everyone, mcDingleHead here. Just checking in.

**Comment by greenaddress** [comment] 2019-08-20 14:05
hi @mcDingleHead 

for the first question, you should look at transaction block height and current blockheight and subtracting the latter with the former - that will tell you the number of confirmations. If a transaction doesn't have a block height than it isn't confirmed (i.e. 0 confirmation)

for the second question, we don't currently limit but we reserve the liberty to in the future, especially if the service is abused - I think if you use the limit you used as an example you will be fine now and in the future.

**Comment by shesek** [comment] 2019-08-28 06:51
>  you should look at .. current blockheight 

@mcDingleHead This is available here: https://blockstream.info/api/blocks/tip/height

Closing this for now, please report back if you have more questions!

**Closed by shesek** 2019-08-28 06:51 UTC

**Comment by mcDingleHead** [comment] 2019-08-29 22:49
Thanks for the response. So just to make sure I understand, obtaining the number of confirmations for a given transaction actually requires _two_ API calls, correct?

(1) https://blockstream.info/api/address/{someAddress}/txs gets the transactions associated with the address. From there I'd cache the block_height of the transaction of interest.

(2) https://blockstream.info/api/blocks/tip/height gets the current block height.

Subtracting the former from the latter yields the number of confirmations. Seems easy enough but just want to confirm there's no way to do this with a single call.

**Comment by shesek** [comment] 2019-09-01 13:57
That is correct, you would need two API calls, exactly as you described.

**Comment by shesek** [comment] 2019-09-01 13:58
Oh, actually,

> Subtracting the former from the latter yields the number of confirmations.

You would need to add 1 to the result of this to get the number of confirmations. i.e. if the tip is at height 100,000 and a tx was included in height 100,000, it has 1 confirmation and not 0.

**Comment by gdassori** [comment] 2019-12-17 10:30
@shesek  @greenaddress I'd love to see this issue reopened. 
I personally think that two calls to have transaction confirmations are inconvenient.

**Comment by shesek** [comment] 2019-12-17 15:22
The reason this was implemented with block height and not the number of confirmations is that you can cache the response with the block height, while using the number of confirmations would require invalidating the cache with every new block. So I think its unlikely that we'll add the number of confirmations, sorry :(
