### ISSUE TITLE
Show txoutproof of transaction [for Liquid Peg-In]

### ISSUE THREAD

**Issue by FrancisPouliot** [Blockstream/esplora#169] opened 2020-02-05 21:42 UTC
When doing a peg-in via Liquid, it is necessary to have the txoutproof in order to claim the pegin. It would be really helpful to have that available in the explorer, because it requires a synced fullnode and not always available. 

Edit: might as well show the transaction hex as well

Thanks!

**Comment by tiero** [comment] 2020-02-28 15:24
I also need this 🙏

**Comment by shesek** [comment] 2020-03-21 09:55
The esplora API does [provide merkle proofs](https://github.com/Blockstream/esplora/blob/master/API.md#get-txtxidmerkle-proof), but using the Electrum merkle proofs format and not bitcoind's.

Back when this was implemented in esplora, there wasn't a Rust implemention for bitcoind-style `merkleblock` proofs -- but I just looked again now, and it seems like [it was since added](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/merkleblock.rs) to rust-bitcoin! Thanks for nudging me to look again :)

Adding this to esplora should be pretty straightforward, I will look into doing this.

Duplicate of #24, will continue tracking this there.

**Closed by shesek** 2020-03-21 09:55 UTC

**Comment by shesek** [comment] 2020-03-21 15:11
Implemented in https://github.com/Blockstream/electrs/commit/cfe94306e22450d347374205637082b25b2cd0c2, available as [`GET /tx/:txid/merkleblock-proof`](https://github.com/blockstream/esplora/blob/master/API.md#get-txtxidmerkleblock-proof).
