### ISSUE TITLE
Verbose transactions are currently unsupported - on 'electrs-esplora' 

### ISSUE THREAD

**Issue by leonardojobim** [Blockstream/esplora#235] opened 2020-08-07 04:25 UTC
When connected to  [ 'electrs-esplora 0.4.1', '1.4' ], the RPC command 'blockchain.transaction.get' with verbose = true returns the error message: verbose transactions are currently unsupported - on 'electrs-esplora 0.4.1', '1.4'  .

**Comment by Axe-gift** [comment] 2020-08-07 20:57
H

**Comment by Axe-gift** [comment] 2020-08-07 20:58
Iam

**Comment by nkuba** [comment] 2022-11-14 13:13
See https://github.com/Blockstream/electrs/pull/36

**Comment by shesek** [comment] 2022-12-04 11:12
Closing as a duplicate of https://github.com/Blockstream/electrs/pull/36.

**Closed by shesek** 2022-12-04 11:12 UTC
