### ISSUE TITLE
Will testnet4 ever be available?

### ISSUE THREAD

**Issue by maxgmer** [Blockstream/esplora#520] opened 2024-08-19 04:40 UTC
Will testnet4 public API endpoint ever be available?

Right now there is only testnet3 under url `https://blockstream.info/testnet/api/`. I think there should be something like `https://blockstream.info/testnet4/api/` as well, because the primary testnet is spammed and never goes below 50sats/vByte, which makes it useless, unless you have a ton of testnet3 BTC.

**Comment by RCasatta** [comment] 2024-08-26 07:40
Yes, but it will take some more time

Some MRs that are needed:
- https://github.com/Blockstream/electrs/pull/91
- https://github.com/ElementsProject/rust-elements/issues/208

**Comment by RCasatta** [comment] 2024-08-26 08:03
duplicate of #497

**Closed by RCasatta** 2024-08-26 08:03 UTC
